@startuml Locacao de veículo

title Locação de veículo

class Cliente{
    - nome: string
    - cpf: int
    - dataNascimento: String
    - CNH: String
    + constructor(nome, cpf, dataNascimento, CNH)
}

class Veiculo{
    - modelo: string
    - ano: Int
    - cor: string
    - disponivel: bool
    + constructor(modelo, ano, cor, disponivel)
}

class Pagamento{
    - modoPagamento: String
    - preco: float
    - valorAdicional: String
    - parcelado: String
    + constructor(modoPagamento, preco, valorAdicional, parcelado)
}

class Locadora{
    - cnpj: String
    - endereco: String
    - qtd_veiculos: int
    - telefone: String
    - funcionario: Funcionario
    + constructor(cnpj, endereco, qtd_veiculos, telefone, Funcionario )
}

class Funcionario{
    - cliente: Cliente
    - matricula: int
    - cargo: String
    - salario: float
    + constructor(Cliente, matricula, cargo, salario)

}



@enduml